### ISSUE TITLE
Add "nearest" and "map" type to export wizard

### ISSUE THREAD

**Issue by uhucrew** [rl3/Sponge-JS-UI#59]
In the export wizard it is not possible to choose dataObj types "nearest" and "map".

For these types an additional wizard-step "location" is necessary.

**Comment by uhucrew** [comment]
API calls finished:

nearest:
/ParameterSetData/getByTagTypeLocation/{tag}/{type}/{lon}/{lat}/{iterator}

map:
/ParameterSetData/getByMapTypeLocation/{mapname}/{type}/{lon}/{lat}/{iterator}

**Comment by steppicrew** [comment]
We should wait and find a proper solution, until the problem rises
