### ISSUE TITLE
Mode: exportWizard: errors from api are not displayed

### ISSUE THREAD

**Issue by uhucrew** [rl3/Sponge-JS-UI#68]
Display API-Errors also in this mode.

To produce an error:
- export climate
- single object
- start: empty
- end: any date
- step: day

**Comment by steppicrew** [comment]
Couldn't find any bug. Works after restarting meteor.
May be it happens, if live system (providing the common mongo-db instance) has been restarted and export wizard has not.
Please check if this bug occurs only in this case!
